import { Google_Sans } from "next/font/google";
import "./globals.css";
import { MountedProvider } from "./_contextx/MountedContext";
import { fetchPrimaryHeader } from "./api/header";
import { fetchSiteSettings } from "./api/footer";
import Footer from "./_components/ui/Footer";
import Header from "./_components/ui/Header";

const GoogleSans = Google_Sans({
  variable: "--font-google-sans",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const primaryHeaderData = await fetchPrimaryHeader();
  const footerData = await fetchSiteSettings();
  return (
    <html
      lang="en"
      className={`${GoogleSans.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <MountedProvider>
          <Header data={primaryHeaderData} />

          {children}
          <Footer data={footerData}/>
        </MountedProvider>
        </body>
    </html>
  );
}
